const SCALE = 0.95;

const TEXT_HEIGHT = 100 * SCALE;

const IMAGE_WIDTH = 200 * SCALE;
const IMAGE_HEIGHT = IMAGE_WIDTH;

export const CARD_HEIGHT = IMAGE_HEIGHT + TEXT_HEIGHT;
export const CARD_WIDTH = IMAGE_WIDTH;

export const STAR_SIZE = 50;
