export const CURIOSITY = {
	COMET_CORE: 'COMET_CORE',
	INVISIBLE_PLANET: 'INVISIBLE_PLANET',
	QUANTUM_MOON: 'QUANTUM_MOON',
	SUNKEN_MODULE: 'SUNKEN_MODULE',
	TIME_LOOP: 'TIME_LOOP',
	VESSEL: 'VESSEL',
}
