name: deploy pages

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/pages.yaml
      - frontend/**
      - "!frontend/scripts/**"
  workflow_dispatch:

env:
  JUST_COLOR: always

jobs:
  build:
    # https://vite.dev/guide/static-deploy.html#github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      VITE_BUILD_VERSION: ${{ github.sha }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: install tools
        run: nix profile add "nixpkgs#just" && just -V

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: install deps
        run: cd frontend && yarn install --frozen-lockfile

      - name: build
        run: cd frontend && yarn build

      - uses: actions/configure-pages@v5

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist
      - name: deploy
        uses: actions/deploy-pages@v4
